### ISSUE TITLE
Suggestion for emulating the open() function in Python (file handling)

### ISSUE THREAD

**Issue by serge-hulne** [goplus/xgo#1320]
### Proposal

A simple suggestion for emulating the open() function of Python.
as in 
```
f = open("demofile.txt", "r")
for x in f:
  print(x)
```

### Background

Aim: Reading a file line by line in order to avoid reading a very large file all at once (to save RAM). 

### Workarounds

reading a file, line by line in a for loop can be done in Go the following way

```
func Open(fname string) (error, *os.File) {
	file, err := os.Open(fname)
	check(err)
	return err, file
}

func Close(file *os.File) {
	file.Close()
}

func ReadLines(f *os.File) chan string {
	ch_lines := make(chan string)
	go func() {
		defer close(ch_lines)
		scanner := bufio.NewScanner(f)
		for scanner.Scan() {
			ch_lines <- scanner.Text()
		}
	}()
	return ch_lines
}
```

Examples of use:
```
	_, f := fi.Open("text.txt")
	lines := fi.ReadLines(f)
        for line := range lines {
              println(line)
        }
```

more details here:
https://github.com/serge-hulne/goutils/blob/main/files/fileutils.go

**Comment by xushiwei** [comment]
```go
import "os"

for line <- os.Stdin {
	println line
}
```

and Go+ provides `open` and `create` builtin functions for os.File.

**Comment by xushiwei** [comment]
% cat foo.gop 

```sh
for line <- open("foo.gop")! {
    println line
}
```

% gop run foo.gop

```go
for line <- open("foo.gop")! {
    println line
}
```

**Comment by xushiwei** [comment]
* based on https://github.com/goplus/xgo/releases/tag/v1.0.0-beta2
* #2841
